# Generated by Django 4.1.6 on 2023-02-13 04:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("PARTY", "Party"),
                            ("CALL", "Call"),
                            ("NATURE", "Nature"),
                            ("SHOPPING", "Shopping"),
                            ("ENTERTAINMENT", "Entertainment"),
                        ],
                        default="PARTY",
                        max_length=50,
                    ),
                ),
                ("activity_date", models.DateField(default=datetime.date.today)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="optionally , add a brief note.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="activities", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "ordering": ["activity_date"],
            },
        ),
    ]
