# Generated by Django 4.1.6 on 2023-02-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0002_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="body",
            new_name="content",
        ),
    ]
